language: python
python:
  - 2.6
  - 2.7
  - pypy
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coveralls
  - python setup.py install
script: python tests.py
after_success: coveralls
notifications:
  email:
    - ema@linux.it
